name: appli_drive_mobile
description: "A version mobile of Appli Drive"

version: 0.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.3
  wakelock_plus: ^1.2.10
  sqflite: ^2.3.2
  path: ^1.9.0
  flutter_localizations:
    sdk: flutter
  audioplayers: ^6.1.0
  screen_state: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/images/icon_app.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/appli_drive_database.db
    - assets/images/
    - assets/images/7code/
    - assets/images/appmons/
    - assets/images/apps/
    - assets/images/flags/
    - assets/images/icons/
    - assets/images/types/
    - assets/sounds/
    - assets/langs/